name: quantum_muscle_website
description: "Quantum Muscle Website"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  eva_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.11
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/font/ubuntu.ttf

  fonts:
    - family: ubuntu
      fonts:
        - asset: assets/font/ubuntu.ttf

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/icon/icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#0F0F0F"
    theme_color: "#0F0F0F"
flutter_native_splash:
  # dart run flutter_native_splash:create
  color: "#0F0F0F"
  image: assets/icon/icon.png
  android: false
  ios: false
  web: true
  web_image_mode: center
  fullscreen: true
